# For any branch except Main, if the Mobirise content has changed
# transfer the files to the preview site 

name: Push Branch to Preview
on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master
    paths:
      - 'project.mobirise'

jobs:
  update_version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Dynamically set TIMESTAMP environment variable
        run: echo "TIMESTAMP=$(date)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'
      - run: echo "${{ env.TIMESTAMP }} - New Branch Push" >> version.txt
      - uses: actions4git/add-commit-push@v1

  modify_footers:
    needs: [update_version]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "footers.sh"
      - name: Dynamically set TIMESTAMP environment variable
        run: echo "TIMESTAMP=$(date)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'
      - name: update footers & version
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "${{ env.TIMESTAMP }} - Modify Content Footers" >> version.txt
      - name: update  version
        if: steps.check_files.outputs.files_exists == 'false'
        run: echo "${{ env.TIMESTAMP }} - No Modify Content Scripts" >> version.txt
      - name: run footers.sh
        if: steps.check_files.outputs.files_exists == 'true'
        run: ./footer.sh
      - uses: actions4git/add-commit-push@v1


  transfer_files:
    needs: [modify_footers]
    runs-on: ubuntu-latest
    env:
      SSH_SERVER: ${{ secrets.ssh_server }}
      SSH_USER: ${{ secrets.ssh_user }}
      SSH_PASSWORD: ${{ secrets.ssh_password }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'
      - run: cat version.txt
